[versions]
android-gradle-plugin = "8.11.2"
kotlin-gradle-plugin = "2.0.21"
google-services = "4.4.2"
firebase-crashlytics-gradle = "3.0.3"
unmock-plugin = "0.8.0"
about-libraries-plugin = "11.2.3"
missing-metadata-guava = "31.1.1"

kotlin-coroutines = "1.8.1"
kotlin-stdlib = "2.0.21"
desugar-jdk-libs = "2.1.5"

core-ktx = "1.15.0"
activity-ktx = "1.9.3"
fragment-ktx = "1.8.6"
appcompat = "1.7.0"
legacy-support-v4 = "1.0.0"
recyclerview = "1.3.2"
constraintlayout = "2.2.1"
preference-ktx = "1.2.1"
biometric = "1.1.0"
multidex = "2.0.1"
work-manager = "2.10.0"
security-crypto = "1.0.0"

material = "1.12.0"
media3 = "1.5.1"
photoview = "2.3.0"
appintro = "6.3.1"
skeletonlayout = "5.0.0"
androidsvg = "1.4"
colorpicker = "0.1.1"

okhttp = "4.12.0"
jmdns = "3.6.1"

play-services-maps = "19.0.0"
osmdroid-android = "6.1.20"

material-about-library = "3.1.2"
about-libraries = "11.2.3"

firebase-bom = "33.7.0"
acra = "5.12.0"

mockito-core = "5.11.0"
mockito-kotlin = "2.2.0"
powermock = "2.0.9"
junit = "4.13.2"
json = "20240303"
espresso = "3.6.1"
junit-ktx = "1.2.1"

androidchart = "3.1.0.26"


[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }

google-services-plugin = { module = "com.google.gms:google-services", version.ref = "google-services" }
firebase-crashlytics-gradle-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
unmock-plugin = { module = "com.github.bjoernq:unmockplugin", version.ref = "unmock-plugin" }
aboutlibraries-plugin = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "about-libraries-plugin" }
missing-metadata-guava-plugin = { module = "de.jjohannes.gradle:missing-metadata-guava", version.ref = "missing-metadata-guava" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-jdk9 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk9", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-stdlib" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy-support-v4" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-manager" }
work-gcm = { module = "androidx.work:work-gcm", version.ref = "work-manager" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }

material = { module = "com.google.android.material:material", version.ref = "material" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
appintro = { module = "com.github.AppIntro:AppIntro", version.ref = "appintro" }
skeletonlayout = { module = "com.faltenreich:skeletonlayout", version.ref = "skeletonlayout" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }
colorpicker = { module = "com.github.chimbori:colorpicker", version.ref = "colorpicker" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okhttp" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
jmdns = { module = "org.jmdns:jmdns", version.ref = "jmdns" }

play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroid-android" }

material-about-library = { module = "com.github.daniel-stoneuk:material-about-library", version.ref = "material-about-library" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }
aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "about-libraries" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

acra-mail = { module = "ch.acra:acra-mail", version.ref = "acra" }
acra-notification = { module = "ch.acra:acra-notification", version.ref = "acra" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito-kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }
powermock-core = { module = "org.powermock:powermock-core", version.ref = "powermock" }
powermock-api-mockito2 = { module = "org.powermock:powermock-api-mockito2", version.ref = "powermock" }
powermock-module-junit4 = { module = "org.powermock:powermock-module-junit4", version.ref = "powermock" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
junit-ktx = { module = "androidx.test.ext:junit", version.ref = "junit-ktx" }

desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }

androidchart = { module = "com.github.AppDevNext:AndroidChart", version.ref = "androidchart" }
